<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reports\Reports.csproj" />
    <ProjectReference Include="..\Millenium.Util\Millenium.Util.csproj" />
  </ItemGroup>
</Project>