<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Millenium.Application\Millenium.Application.csproj" />
    <ProjectReference Include="..\Millenium.Domain\Millenium.Domain.csproj" />
    <ProjectReference Include="..\Millenium.Infra.Data\Millenium.Infra.Data.csproj" />
    <ProjectReference Include="..\Millenium.Util\Millenium.Util.csproj" />
  </ItemGroup>
</Project>