<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="wwwroot\Content\Login\bootstrap.min.css" />
    <None Include="wwwroot\Content\Login\styles.css" />
    <None Include="wwwroot\Content\premium-theme.css" />
    <None Include="wwwroot\Content\themes\base\accordion.css" />
    <None Include="wwwroot\Content\themes\base\all.css" />
    <None Include="wwwroot\Content\themes\base\autocomplete.css" />
    <None Include="wwwroot\Content\themes\base\base.css" />
    <None Include="wwwroot\Content\themes\base\button.css" />
    <None Include="wwwroot\Content\themes\base\core.css" />
    <None Include="wwwroot\Content\themes\base\datepicker.css" />
    <None Include="wwwroot\Content\themes\base\dialog.css" />
    <None Include="wwwroot\Content\themes\base\draggable.css" />
    <None Include="wwwroot\Content\themes\base\images\ui-bg_flat_0_aaaaaa_40x100.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-bg_flat_75_ffffff_40x100.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-bg_glass_55_fbf9ee_1x400.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-bg_glass_65_ffffff_1x400.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-bg_glass_75_dadada_1x400.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-bg_glass_75_e6e6e6_1x400.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-bg_glass_95_fef1ec_1x400.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-bg_highlight-soft_75_cccccc_1x100.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_222222_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_2e83ff_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_444444_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_454545_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_555555_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_777620_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_777777_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_888888_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_cc0000_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_cd0a0a_256x240.png" />
    <None Include="wwwroot\Content\themes\base\images\ui-icons_ffffff_256x240.png" />
    <None Include="wwwroot\Content\themes\base\jquery-ui.css" />
    <None Include="wwwroot\Content\themes\base\jquery-ui.min.css" />
    <None Include="wwwroot\Content\themes\base\menu.css" />
    <None Include="wwwroot\Content\themes\base\progressbar.css" />
    <None Include="wwwroot\Content\themes\base\resizable.css" />
    <None Include="wwwroot\Content\themes\base\selectable.css" />
    <None Include="wwwroot\Content\themes\base\selectmenu.css" />
    <None Include="wwwroot\Content\themes\base\slider.css" />
    <None Include="wwwroot\Content\themes\base\sortable.css" />
    <None Include="wwwroot\Content\themes\base\spinner.css" />
    <None Include="wwwroot\Content\themes\base\tabs.css" />
    <None Include="wwwroot\Content\themes\base\theme.css" />
    <None Include="wwwroot\Content\themes\base\tooltip.css" />
    <None Include="wwwroot\css\AdminLTE.css" />
    <None Include="wwwroot\css\bootstrap-slider\slider.css" />
    <None Include="wwwroot\css\bootstrap-wysihtml5\bootstrap3-wysihtml5.css" />
    <None Include="wwwroot\css\bootstrap-wysihtml5\bootstrap3-wysihtml5.min.css" />
    <None Include="wwwroot\css\bootstrap.css" />
    <None Include="wwwroot\css\bootstrap.min.css" />
    <None Include="wwwroot\css\bootstrap3.3.1\bootstrap.css" />
    <None Include="wwwroot\css\colorpicker\bootstrap-colorpicker.css" />
    <None Include="wwwroot\css\colorpicker\bootstrap-colorpicker.min.css" />
    <None Include="wwwroot\css\datatables\dataTables.bootstrap.css" />
    <None Include="wwwroot\css\datatables\images\sort_asc.png" />
    <None Include="wwwroot\css\datatables\images\sort_asc_disabled.png" />
    <None Include="wwwroot\css\datatables\images\sort_both.png" />
    <None Include="wwwroot\css\datatables\images\sort_desc.png" />
    <None Include="wwwroot\css\datatables\images\sort_desc_disabled.png" />
    <None Include="wwwroot\css\daterangepicker\daterangepicker-bs3.css" />
    <None Include="wwwroot\css\font-awesome.css" />
    <None Include="wwwroot\css\font-awesome.min.css" />
    <None Include="wwwroot\css\fullcalendar\fullcalendar.css" />
    <None Include="wwwroot\css\fullcalendar\fullcalendar.print.css" />
    <None Include="wwwroot\css\Graficos.css" />
    <None Include="wwwroot\css\iCheck\all.css" />
    <None Include="wwwroot\css\iCheck\flat\aero%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\aero.css" />
    <None Include="wwwroot\css\iCheck\flat\aero.png" />
    <None Include="wwwroot\css\iCheck\flat\blue%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\blue.css" />
    <None Include="wwwroot\css\iCheck\flat\blue.png" />
    <None Include="wwwroot\css\iCheck\flat\flat%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\flat.css" />
    <None Include="wwwroot\css\iCheck\flat\flat.png" />
    <None Include="wwwroot\css\iCheck\flat\green%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\green.css" />
    <None Include="wwwroot\css\iCheck\flat\green.png" />
    <None Include="wwwroot\css\iCheck\flat\grey%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\grey.css" />
    <None Include="wwwroot\css\iCheck\flat\grey.png" />
    <None Include="wwwroot\css\iCheck\flat\orange%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\orange.css" />
    <None Include="wwwroot\css\iCheck\flat\orange.png" />
    <None Include="wwwroot\css\iCheck\flat\pink%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\pink.css" />
    <None Include="wwwroot\css\iCheck\flat\pink.png" />
    <None Include="wwwroot\css\iCheck\flat\purple%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\purple.css" />
    <None Include="wwwroot\css\iCheck\flat\purple.png" />
    <None Include="wwwroot\css\iCheck\flat\red%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\red.css" />
    <None Include="wwwroot\css\iCheck\flat\red.png" />
    <None Include="wwwroot\css\iCheck\flat\yellow%402x.png" />
    <None Include="wwwroot\css\iCheck\flat\yellow.css" />
    <None Include="wwwroot\css\iCheck\flat\yellow.png" />
    <None Include="wwwroot\css\iCheck\flat\_all.css" />
    <None Include="wwwroot\css\iCheck\futurico\futurico%402x.png" />
    <None Include="wwwroot\css\iCheck\futurico\futurico.css" />
    <None Include="wwwroot\css\iCheck\futurico\futurico.png" />
    <None Include="wwwroot\css\iCheck\line\aero.css" />
    <None Include="wwwroot\css\iCheck\line\blue.css" />
    <None Include="wwwroot\css\iCheck\line\green.css" />
    <None Include="wwwroot\css\iCheck\line\grey.css" />
    <None Include="wwwroot\css\iCheck\line\line%402x.png" />
    <None Include="wwwroot\css\iCheck\line\line.css" />
    <None Include="wwwroot\css\iCheck\line\line.png" />
    <None Include="wwwroot\css\iCheck\line\orange.css" />
    <None Include="wwwroot\css\iCheck\line\pink.css" />
    <None Include="wwwroot\css\iCheck\line\purple.css" />
    <None Include="wwwroot\css\iCheck\line\red.css" />
    <None Include="wwwroot\css\iCheck\line\yellow.css" />
    <None Include="wwwroot\css\iCheck\line\_all.css" />
    <None Include="wwwroot\css\iCheck\minimal\aero%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\aero.css" />
    <None Include="wwwroot\css\iCheck\minimal\aero.png" />
    <None Include="wwwroot\css\iCheck\minimal\blue%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\blue.css" />
    <None Include="wwwroot\css\iCheck\minimal\blue.png" />
    <None Include="wwwroot\css\iCheck\minimal\green%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\green.css" />
    <None Include="wwwroot\css\iCheck\minimal\green.png" />
    <None Include="wwwroot\css\iCheck\minimal\grey%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\grey.css" />
    <None Include="wwwroot\css\iCheck\minimal\grey.png" />
    <None Include="wwwroot\css\iCheck\minimal\minimal%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\minimal.css" />
    <None Include="wwwroot\css\iCheck\minimal\minimal.png" />
    <None Include="wwwroot\css\iCheck\minimal\orange%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\orange.css" />
    <None Include="wwwroot\css\iCheck\minimal\orange.png" />
    <None Include="wwwroot\css\iCheck\minimal\pink%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\pink.css" />
    <None Include="wwwroot\css\iCheck\minimal\pink.png" />
    <None Include="wwwroot\css\iCheck\minimal\purple%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\purple.css" />
    <None Include="wwwroot\css\iCheck\minimal\purple.png" />
    <None Include="wwwroot\css\iCheck\minimal\red%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\red.css" />
    <None Include="wwwroot\css\iCheck\minimal\red.png" />
    <None Include="wwwroot\css\iCheck\minimal\yellow%402x.png" />
    <None Include="wwwroot\css\iCheck\minimal\yellow.css" />
    <None Include="wwwroot\css\iCheck\minimal\yellow.png" />
    <None Include="wwwroot\css\iCheck\minimal\_all.css" />
    <None Include="wwwroot\css\iCheck\polaris\polaris%402x.png" />
    <None Include="wwwroot\css\iCheck\polaris\polaris.css" />
    <None Include="wwwroot\css\iCheck\polaris\polaris.png" />
    <None Include="wwwroot\css\iCheck\square\aero%402x.png" />
    <None Include="wwwroot\css\iCheck\square\aero.css" />
    <None Include="wwwroot\css\iCheck\square\aero.png" />
    <None Include="wwwroot\css\iCheck\square\blue%402x.png" />
    <None Include="wwwroot\css\iCheck\square\blue.css" />
    <None Include="wwwroot\css\iCheck\square\blue.png" />
    <None Include="wwwroot\css\iCheck\square\green%402x.png" />
    <None Include="wwwroot\css\iCheck\square\green.css" />
    <None Include="wwwroot\css\iCheck\square\green.png" />
    <None Include="wwwroot\css\iCheck\square\grey%402x.png" />
    <None Include="wwwroot\css\iCheck\square\grey.css" />
    <None Include="wwwroot\css\iCheck\square\grey.png" />
    <None Include="wwwroot\css\iCheck\square\orange%402x.png" />
    <None Include="wwwroot\css\iCheck\square\orange.css" />
    <None Include="wwwroot\css\iCheck\square\orange.png" />
    <None Include="wwwroot\css\iCheck\square\pink%402x.png" />
    <None Include="wwwroot\css\iCheck\square\pink.css" />
    <None Include="wwwroot\css\iCheck\square\pink.png" />
    <None Include="wwwroot\css\iCheck\square\purple%402x.png" />
    <None Include="wwwroot\css\iCheck\square\purple.css" />
    <None Include="wwwroot\css\iCheck\square\purple.png" />
    <None Include="wwwroot\css\iCheck\square\red%402x.png" />
    <None Include="wwwroot\css\iCheck\square\red.css" />
    <None Include="wwwroot\css\iCheck\square\red.png" />
    <None Include="wwwroot\css\iCheck\square\square%402x.png" />
    <None Include="wwwroot\css\iCheck\square\square.css" />
    <None Include="wwwroot\css\iCheck\square\square.png" />
    <None Include="wwwroot\css\iCheck\square\yellow%402x.png" />
    <None Include="wwwroot\css\iCheck\square\yellow.css" />
    <None Include="wwwroot\css\iCheck\square\yellow.png" />
    <None Include="wwwroot\css\iCheck\square\_all.css" />
    <None Include="wwwroot\css\images\animated-overlay.gif" />
    <None Include="wwwroot\css\images\ui-bg_flat_0_aaaaaa_40x100.png" />
    <None Include="wwwroot\css\images\ui-bg_flat_55_fbec88_40x100.png" />
    <None Include="wwwroot\css\images\ui-bg_glass_75_d0e5f5_1x400.png" />
    <None Include="wwwroot\css\images\ui-bg_glass_85_dfeffc_1x400.png" />
    <None Include="wwwroot\css\images\ui-bg_glass_95_fef1ec_1x400.png" />
    <None Include="wwwroot\css\images\ui-bg_gloss-wave_55_5c9ccc_500x100.png" />
    <None Include="wwwroot\css\images\ui-bg_inset-hard_100_f5f8f9_1x100.png" />
    <None Include="wwwroot\css\images\ui-bg_inset-hard_100_fcfdfd_1x100.png" />
    <None Include="wwwroot\css\images\ui-icons_217bc0_256x240.png" />
    <None Include="wwwroot\css\images\ui-icons_2e83ff_256x240.png" />
    <None Include="wwwroot\css\images\ui-icons_469bdd_256x240.png" />
    <None Include="wwwroot\css\images\ui-icons_6da8d5_256x240.png" />
    <None Include="wwwroot\css\images\ui-icons_cd0a0a_256x240.png" />
    <None Include="wwwroot\css\images\ui-icons_d8e7f3_256x240.png" />
    <None Include="wwwroot\css\images\ui-icons_f9bd01_256x240.png" />
    <None Include="wwwroot\css\ionicons.css" />
    <None Include="wwwroot\css\ionicons.min.css" />
    <None Include="wwwroot\css\ionslider\ion.rangeSlider.css" />
    <None Include="wwwroot\css\ionslider\ion.rangeSlider.skinFlat.css" />
    <None Include="wwwroot\css\ionslider\ion.rangeSlider.skinNice.css" />
    <None Include="wwwroot\css\jQueryUI\images\animated-overlay.gif" />
    <None Include="wwwroot\css\jQueryUI\images\ui-bg_flat_0_aaaaaa_40x100.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-bg_flat_100_e6e7e8_40x100.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-bg_flat_100_f56954_40x100.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-bg_flat_55_f39c12_40x100.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-bg_flat_65_ffffff_40x100.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-bg_flat_75_dadada_40x100.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-bg_flat_75_e6e6e6_40x100.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-bg_flat_75_ffffff_40x100.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-icons_222222_256x240.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-icons_454545_256x240.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-icons_888888_256x240.png" />
    <None Include="wwwroot\css\jQueryUI\images\ui-icons_ffffff_256x240.png" />
    <None Include="wwwroot\css\jQueryUI\jquery-ui-1.10.3.custom.css" />
    <None Include="wwwroot\css\jQueryUI\jquery-ui-1.10.3.custom.min.css" />
    <None Include="wwwroot\css\jvectormap\jquery-jvectormap-1.2.2.css" />
    <None Include="wwwroot\css\morris\morris.css" />
    <None Include="wwwroot\css\painel-moderno.css" />
    <None Include="wwwroot\css\site-institucional.css" />
    <None Include="wwwroot\css\timepicker\bootstrap-timepicker.css" />
    <None Include="wwwroot\css\timepicker\bootstrap-timepicker.min.css" />
    <None Include="wwwroot\css\token-input-facebook.css" />
    <None Include="wwwroot\css\token-input.css" />
    <None Include="wwwroot\fonts\fontawesome-webfont.eot" />
    <None Include="wwwroot\fonts\fontawesome-webfont.svg" />
    <None Include="wwwroot\fonts\fontawesome-webfont.ttf" />
    <None Include="wwwroot\fonts\fontawesome-webfont.woff" />
    <None Include="wwwroot\fonts\FontAwesome.otf" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.eot" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.svg" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.ttf" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.woff" />
    <None Include="wwwroot\fonts\ionicons.eot" />
    <None Include="wwwroot\fonts\ionicons.svg" />
    <None Include="wwwroot\fonts\ionicons.ttf" />
    <None Include="wwwroot\fonts\ionicons.woff" />
    <None Include="wwwroot\img\accent.png" />
    <None Include="wwwroot\img\adicionar.png" />
    <None Include="wwwroot\img\ajax-loader.gif" />
    <None Include="wwwroot\img\ajax-loader1.gif" />
    <None Include="wwwroot\img\avatar.png" />
    <None Include="wwwroot\img\avatar04.png" />
    <None Include="wwwroot\img\avatar2.png" />
    <None Include="wwwroot\img\avatar3.png" />
    <None Include="wwwroot\img\avatar5.png" />
    <None Include="wwwroot\img\blur-background04.jpg" />
    <None Include="wwwroot\img\blur-background08.jpg" />
    <None Include="wwwroot\img\blur-background09.jpg" />
    <None Include="wwwroot\img\bootstrap-colorpicker\alpha-horizontal.png" />
    <None Include="wwwroot\img\bootstrap-colorpicker\alpha.png" />
    <None Include="wwwroot\img\bootstrap-colorpicker\hue-horizontal.png" />
    <None Include="wwwroot\img\bootstrap-colorpicker\hue.png" />
    <None Include="wwwroot\img\bootstrap-colorpicker\saturation.png" />
    <None Include="wwwroot\img\bullet.png" />
    <None Include="wwwroot\img\captura-antiga.png" />
    <None Include="wwwroot\img\credit\american-express.png" />
    <None Include="wwwroot\img\credit\cirrus.png" />
    <None Include="wwwroot\img\credit\mastercard.png" />
    <None Include="wwwroot\img\credit\mestro.png" />
    <None Include="wwwroot\img\credit\paypal.png" />
    <None Include="wwwroot\img\credit\paypal2.png" />
    <None Include="wwwroot\img\credit\visa.png" />
    <None Include="wwwroot\img\editar.png" />
    <None Include="wwwroot\img\excluir.png" />
    <None Include="wwwroot\img\heroAccent.png" />
    <None Include="wwwroot\img\icons.png" />
    <None Include="wwwroot\img\loading-sm.gif" />
    <None Include="wwwroot\img\loading.gif" />
    <None Include="wwwroot\img\logo_bw.png" />
    <None Include="wwwroot\img\logo_cliente_login.png" />
    <None Include="wwwroot\img\logo_color.png" />
    <None Include="wwwroot\img\millenium-logo-novo.png" />
    <None Include="wwwroot\img\millenium-logo-sembg.png" />
    <None Include="wwwroot\img\millenium-logo.jpg" />
    <None Include="wwwroot\img\millenium-logo.png" />
    <None Include="wwwroot\img\rodape.png" />
    <None Include="wwwroot\img\sprite-skin-flat.png" />
    <None Include="wwwroot\img\sprite-skin-nice.png" />
    <None Include="wwwroot\img\user-bg.png" />
    <None Include="wwwroot\img\user.jpg" />
    <None Include="wwwroot\img\user2.jpg" />
    <None Include="wwwroot\js\AdminLTE\app.js" />
    <None Include="wwwroot\js\AdminLTE\dashboard.js" />
    <None Include="wwwroot\js\bootstrap.js" />
    <None Include="wwwroot\js\funcoes\funcoes.js" />
    <None Include="wwwroot\js\funcoes\jquery.tokeninput.js" />
    <None Include="wwwroot\js\Graficos\exporting.js" />
    <None Include="wwwroot\js\Graficos\Graficos.js" />
    <None Include="wwwroot\js\Graficos\highcharts-3d.js" />
    <None Include="wwwroot\js\Graficos\highcharts.js" />
    <None Include="wwwroot\js\jquery-ui-1.10.3.js" />
    <None Include="wwwroot\js\jquery-ui-1.10.3.min.js" />
    <None Include="wwwroot\js\jquery.min.js" />
    <None Include="wwwroot\js\jquery\jquery-1.8.2.intellisense.js" />
    <None Include="wwwroot\js\jquery\jquery-1.8.2.js" />
    <None Include="wwwroot\js\jquery\jquery-1.8.2.min.js" />
    <None Include="wwwroot\js\jquery\jquery-ui-1.8.24.js" />
    <None Include="wwwroot\js\jquery\jquery-ui-1.8.24.min.js" />
    <None Include="wwwroot\js\jquery\jquery.maskedinput-1.2.2.min.js" />
    <None Include="wwwroot\js\jquery\jquery.ui.autocomplete.scroll.min.js" />
    <None Include="wwwroot\js\jquery\jquery.unobtrusive-ajax.js" />
    <None Include="wwwroot\js\jquery\jquery.unobtrusive-ajax.min.js" />
    <None Include="wwwroot\js\jquery\jquery.validate-vsdoc.js" />
    <None Include="wwwroot\js\jquery\jquery.validate.js" />
    <None Include="wwwroot\js\jquery\jquery.validate.min.js" />
    <None Include="wwwroot\js\jquery\jquery.validate.unobtrusive.js" />
    <None Include="wwwroot\js\jquery\jquery.validate.unobtrusive.min.js" />
    <None Include="wwwroot\js\jsmascara.js" />
    <None Include="wwwroot\js\plugins\bootstrap-slider\bootstrap-slider.js" />
    <None Include="wwwroot\js\plugins\bootstrap-wysihtml5\bootstrap3-wysihtml5.all.min.js" />
    <None Include="wwwroot\js\plugins\bootstrap-wysihtml5\bootstrap3-wysihtml5.js" />
    <None Include="wwwroot\js\plugins\ckeditor\adapters\jquery.js" />
    <None Include="wwwroot\js\plugins\ckeditor\build-config.js" />
    <None Include="wwwroot\js\plugins\ckeditor\CHANGES.md" />
    <None Include="wwwroot\js\plugins\ckeditor\ckeditor.js" />
    <None Include="wwwroot\js\plugins\ckeditor\config.js" />
    <None Include="wwwroot\js\plugins\ckeditor\contents.css" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\af.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ar.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\bg.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\bn.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\bs.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ca.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\cs.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\cy.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\da.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\de.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\el.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\en-au.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\en-ca.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\en-gb.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\en.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\eo.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\es.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\et.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\eu.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\fa.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\fi.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\fo.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\fr-ca.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\fr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\gl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\gu.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\he.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\hi.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\hr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\hu.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\id.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\is.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\it.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ja.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ka.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\km.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ko.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ku.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\lt.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\lv.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\mk.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\mn.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ms.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\nb.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\nl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\no.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\pl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\pt-br.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\pt.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ro.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ru.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\si.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\sk.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\sl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\sq.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\sr-latn.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\sr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\sv.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\th.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\tr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\ug.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\uk.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\vi.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\zh-cn.js" />
    <None Include="wwwroot\js\plugins\ckeditor\lang\zh.js" />
    <None Include="wwwroot\js\plugins\ckeditor\LICENSE.md" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\a11yhelp.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\ar.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\bg.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\ca.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\cs.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\cy.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\da.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\de.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\el.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\en.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\eo.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\es.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\et.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\fa.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\fi.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\fr-ca.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\fr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\gl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\gu.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\he.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\hi.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\hr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\hu.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\id.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\it.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\ja.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\km.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\ko.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\ku.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\lt.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\lv.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\mk.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\mn.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\nb.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\nl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\no.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\pl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\pt-br.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\pt.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\ro.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\ru.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\si.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\sk.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\sl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\sq.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\sr-latn.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\sr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\sv.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\th.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\tr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\ug.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\uk.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\vi.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\zh-cn.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\zh.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\a11yhelp\dialogs\lang\_translationstatus.txt" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\about\dialogs\about.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\about\dialogs\hidpi\logo_ckeditor.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\about\dialogs\logo_ckeditor.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\clipboard\dialogs\paste.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\dialog\dialogDefinition.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\fakeobjects\images\spacer.gif" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\icons.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\icons_hidpi.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\image\dialogs\image.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\image\images\noimage.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\link\dialogs\anchor.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\link\dialogs\link.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\link\images\anchor.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\link\images\hidpi\anchor.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\magicline\images\hidpi\icon.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\magicline\images\icon.png" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\pastefromword\filter\default.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\scayt\dialogs\options.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\scayt\dialogs\toolbar.css" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\scayt\LICENSE.md" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\scayt\README.md" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\ar.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\bg.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\ca.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\cs.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\cy.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\de.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\el.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\en.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\eo.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\es.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\et.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\fa.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\fi.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\fr-ca.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\fr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\gl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\he.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\hr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\hu.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\id.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\it.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\ja.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\km.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\ku.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\lv.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\nb.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\nl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\no.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\pl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\pt-br.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\pt.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\ru.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\si.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\sk.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\sl.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\sq.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\sv.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\th.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\tr.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\ug.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\uk.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\vi.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\zh-cn.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\zh.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\lang\_translationstatus.txt" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\specialchar\dialogs\specialchar.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\tabletools\dialogs\tableCell.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\table\dialogs\table.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\wsc\dialogs\ciframe.html" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\wsc\dialogs\tmp.html" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\wsc\dialogs\tmpFrameset.html" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\wsc\dialogs\wsc.css" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\wsc\dialogs\wsc.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\wsc\dialogs\wsc_ie.js" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\wsc\LICENSE.md" />
    <None Include="wwwroot\js\plugins\ckeditor\plugins\wsc\README.md" />
    <None Include="wwwroot\js\plugins\ckeditor\README.md" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\dialog.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\dialog_ie.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\dialog_ie7.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\dialog_ie8.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\dialog_iequirks.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\dialog_opera.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\editor.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\editor_gecko.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\editor_ie.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\editor_ie7.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\editor_ie8.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\editor_iequirks.css" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\icons.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\icons_hidpi.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\arrow.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\close.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\hidpi\close.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\hidpi\lock-open.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\hidpi\lock.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\hidpi\refresh.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\lock-open.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\lock.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\images\refresh.png" />
    <None Include="wwwroot\js\plugins\ckeditor\skins\moono\readme.md" />
    <None Include="wwwroot\js\plugins\ckeditor\styles.js" />
    <None Include="wwwroot\js\plugins\colorpicker\bootstrap-colorpicker.js" />
    <None Include="wwwroot\js\plugins\colorpicker\bootstrap-colorpicker.min.js" />
    <None Include="wwwroot\js\plugins\datatables\dataTables.bootstrap.js" />
    <None Include="wwwroot\js\plugins\datatables\jquery.dataTables.js" />
    <None Include="wwwroot\js\plugins\daterangepicker\daterangepicker.js" />
    <None Include="wwwroot\js\plugins\flot\excanvas.js" />
    <None Include="wwwroot\js\plugins\flot\excanvas.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.colorhelpers.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.colorhelpers.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.canvas.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.canvas.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.categories.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.categories.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.crosshair.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.crosshair.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.errorbars.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.errorbars.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.fillbetween.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.fillbetween.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.image.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.image.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.navigate.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.navigate.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.pie.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.pie.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.resize.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.resize.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.selection.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.selection.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.stack.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.stack.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.symbol.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.symbol.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.threshold.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.threshold.min.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.time.js" />
    <None Include="wwwroot\js\plugins\flot\jquery.flot.time.min.js" />
    <None Include="wwwroot\js\plugins\fullcalendar\fullcalendar.js" />
    <None Include="wwwroot\js\plugins\fullcalendar\fullcalendar.min.js" />
    <None Include="wwwroot\js\plugins\iCheck\icheck.js" />
    <None Include="wwwroot\js\plugins\iCheck\icheck.min.js" />
    <None Include="wwwroot\js\plugins\input-mask\jquery.inputmask.date.extensions.js" />
    <None Include="wwwroot\js\plugins\input-mask\jquery.inputmask.extensions.js" />
    <None Include="wwwroot\js\plugins\input-mask\jquery.inputmask.js" />
    <None Include="wwwroot\js\plugins\input-mask\jquery.inputmask.numeric.extensions.js" />
    <None Include="wwwroot\js\plugins\input-mask\jquery.inputmask.phone.extensions.js" />
    <None Include="wwwroot\js\plugins\input-mask\jquery.inputmask.regex.extensions.js" />
    <None Include="wwwroot\js\plugins\input-mask\phone-codes\readme.txt" />
    <None Include="wwwroot\js\plugins\ionslider\ion.rangeSlider.min.js" />
    <None Include="wwwroot\js\plugins\jqueryKnob\jquery.knob.js" />
    <None Include="wwwroot\js\plugins\jvectormap\jquery-jvectormap-1.2.2.min.js" />
    <None Include="wwwroot\js\plugins\jvectormap\jquery-jvectormap-world-mill-en.js" />
    <None Include="wwwroot\js\plugins\misc\html5shiv.js" />
    <None Include="wwwroot\js\plugins\misc\jquery.ba-resize.min.js" />
    <None Include="wwwroot\js\plugins\misc\jquery.placeholder.js" />
    <None Include="wwwroot\js\plugins\misc\modernizr.min.js" />
    <None Include="wwwroot\js\plugins\misc\respond.min.js" />
    <None Include="wwwroot\js\plugins\morris\morris.js" />
    <None Include="wwwroot\js\plugins\morris\morris.min.js" />
    <None Include="wwwroot\js\plugins\slimScroll\jquery.slimscroll.js" />
    <None Include="wwwroot\js\plugins\slimScroll\jquery.slimscroll.min.js" />
    <None Include="wwwroot\js\plugins\sparkline\jquery.sparkline.js" />
    <None Include="wwwroot\js\plugins\sparkline\jquery.sparkline.min.js" />
    <None Include="wwwroot\js\plugins\timepicker\bootstrap-timepicker.js" />
    <None Include="wwwroot\js\plugins\timepicker\bootstrap-timepicker.min.js" />
    <None Include="wwwroot\js\raphael-min.js" />
    <None Include="wwwroot\js\site-institucional.js" />
    <None Include="wwwroot\less\404_500_errors.less" />
    <None Include="wwwroot\less\AdminLTE.less" />
    <None Include="wwwroot\less\alerts.less" />
    <None Include="wwwroot\less\bootstrap-social.less" />
    <None Include="wwwroot\less\boxes.less" />
    <None Include="wwwroot\less\buttons.less" />
    <None Include="wwwroot\less\callout.less" />
    <None Include="wwwroot\less\core.less" />
    <None Include="wwwroot\less\dropdown.less" />
    <None Include="wwwroot\less\forms.less" />
    <None Include="wwwroot\less\header.less" />
    <None Include="wwwroot\less\iCheck.less" />
    <None Include="wwwroot\less\invoice.less" />
    <None Include="wwwroot\less\lockscreen.less" />
    <None Include="wwwroot\less\login_and_register.less" />
    <None Include="wwwroot\less\mailbox.less" />
    <None Include="wwwroot\less\mixins.less" />
    <None Include="wwwroot\less\navs.less" />
    <None Include="wwwroot\less\pace.less" />
    <None Include="wwwroot\less\progress-bars.less" />
    <None Include="wwwroot\less\sidebar.less" />
    <None Include="wwwroot\less\skins.less" />
    <None Include="wwwroot\less\small-box.less" />
    <None Include="wwwroot\less\timeline.less" />
    <None Include="wwwroot\less\vars.less" />
    <None Include="wwwroot\Scripts\jquery-3.4.1.intellisense.js" />
    <None Include="wwwroot\Scripts\jquery-3.4.1.js" />
    <None Include="wwwroot\Scripts\jquery-3.4.1.min.js" />
    <None Include="wwwroot\Scripts\jquery-3.4.1.min.map" />
    <None Include="wwwroot\Scripts\jquery-3.4.1.slim.js" />
    <None Include="wwwroot\Scripts\jquery-3.4.1.slim.min.js" />
    <None Include="wwwroot\Scripts\jquery-3.4.1.slim.min.map" />
    <None Include="wwwroot\Scripts\jquery-ui-1.12.1.js" />
    <None Include="wwwroot\Scripts\jquery-ui-1.12.1.min.js" />
    <None Include="wwwroot\Scripts\jquery.unobtrusive-ajax.js" />
    <None Include="wwwroot\Scripts\jquery.unobtrusive-ajax.min.js" />
    <None Include="wwwroot\Scripts\jquery.validate-vsdoc.js" />
    <None Include="wwwroot\Scripts\jquery.validate.js" />
    <None Include="wwwroot\Scripts\jquery.validate.min.js" />
    <None Include="wwwroot\Scripts\jquery.validate.unobtrusive.js" />
    <None Include="wwwroot\Scripts\jquery.validate.unobtrusive.min.js" />
    <None Include="wwwroot\Scripts\knockout-3.5.0.debug.js" />
    <None Include="wwwroot\Scripts\knockout-3.5.0.js" />
    <None Include="wwwroot\Scripts\modernizr-2.8.3.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Millenium.Application\Millenium.Application.csproj" />
    <ProjectReference Include="..\Millenium.Domain\Millenium.Domain.csproj" />
    <ProjectReference Include="..\Millenium.Infra.Data\Millenium.Infra.Data.csproj" />
    <ProjectReference Include="..\Millenium.Util\Millenium.Util.csproj" />
  </ItemGroup>
</Project>