CREATE TABLE [dbo].[Solicitacao] (
    [IdSolicitacao]      INT          IDENTITY (1, 1) NOT NULL,
    [IdCliente]          INT          NULL,
    [IdUsuarioCriacao]   INT          NULL,
    [IdUsuarioAlteracao] INT          NULL,
    [IdUsuarioExclusao]  INT          NULL,
    [DataHoraCriacao]    DATETIME     NULL,
    [DataHoraAlteracao]  DATETIME     NULL,
    [DataHoraExclusao]   DATETIME     NULL,
    [Excluido]           BIT          NULL,
    [Nome]               VARCHAR (50) NOT NULL,
    [DataNascimento]     DATETIME     NOT NULL,
    [Cpf]                VARCHAR (15) NOT NULL,
    [Rg]                 VARCHAR (10) NOT NULL,
    [NomePai]            VARCHAR (50) NOT NULL,
    [NomeMae]            VARCHAR (50) NOT NULL,
    [IdTipoSolicitacao]  INT          NOT NULL,
    [IdEndereco]         INT          NULL,
    [NumeroSequencial]   VARCHAR (50) NULL,
    [Sequencia]          INT          NULL,
    [Ano]                INT          NULL,
    [Local] VARCHAR(50) NULL, 
    [Resposta] VARCHAR(5000) NULL, 
    CONSTRAINT [PK_Solicitacao] PRIMARY KEY CLUSTERED ([IdSolicitacao] ASC),
    CONSTRAINT [FK_Solicitacao_Cliente] FOREIGN KEY ([IdCliente]) REFERENCES [dbo].[Cliente] ([IdCliente]),
    CONSTRAINT [FK_Solicitacao_TipoSolicitacao] FOREIGN KEY ([IdTipoSolicitacao]) REFERENCES [dbo].[TipoSolicitacao] ([IdTipoSolicitacao]),
    CONSTRAINT [FK_Solicitacao_Usuario_Alteracao] FOREIGN KEY ([IdUsuarioAlteracao]) REFERENCES [dbo].[Usuario] ([IdUsuario]),
    CONSTRAINT [FK_Solicitacao_Usuario_Criacao] FOREIGN KEY ([IdUsuarioCriacao]) REFERENCES [dbo].[Usuario] ([IdUsuario]),
    CONSTRAINT [FK_Solicitacao_Usuario_Exclusao] FOREIGN KEY ([IdUsuarioExclusao]) REFERENCES [dbo].[Usuario] ([IdUsuario])
);

